version: '3.7'

services:
  jenkins-test-server:
    image: jenkins/jenkins:lts
    privileged: true

    ports:
      - 8081:8080
      - 50001:50000

    container_name: test-server

    volumes:
      - ./App:/Project

    networks:
      jenkins-net:
        ipv4_address: 172.20.127.0


  sonarqube:
    image: sonarqube:community
    depends_on:
      - sonar-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonar/sonarqube_data:/opt/sonarqube/data
      - ./sonar/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonar/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

    networks:
      - jenkins-net
  
  sonar-db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    ports:
      - "5435:5432"
    volumes:
      - ./sonar/sonar-db/postgresql:/var/lib/postgresql
      - ./sonar/sonar-db/data:/var/lib/postgresql/data

    networks:
      - jenkins-net

networks:
  jenkins-net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
